# Generated by Django 4.1.7 on 2023-03-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrirtion',
            new_name='description',
        ),
    ]
