# Generated by Django 4.1.7 on 2023-03-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_descrirtion_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compleated',
            new_name='is_completed',
        ),
    ]
